package oracle.apps.awcust.awcustPerson.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class awcustManagerVORowImpl extends OAViewRowImpl 
{
  protected static final int LASTNAME = 0;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public awcustManagerVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute LastName
   */
  public String getLastName()
  {
    return (String)getAttributeInternal(LASTNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LastName
   */
  public void setLastName(String value)
  {
    setAttributeInternal(LASTNAME, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LASTNAME:
        return getLastName();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LASTNAME:
        setLastName((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}