package oracle.apps.awcust.person.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineManagerLovVORowImpl extends OAViewRowImpl {
    public static final int LINEMANAGER = 0;

    /**This is the default constructor (do not remove)
     */
    public LineManagerLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LineManager
     */
    public String getLineManager() {
        return (String) getAttributeInternal(LINEMANAGER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineManager
     */
    public void setLineManager(String value) {
        setAttributeInternal(LINEMANAGER, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINEMANAGER:
            return getLineManager();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
