package oracle.apps.awcust.ar.reports.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OADBTransactionImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.apps.xdo.oa.util.DataTemplate;
import java.sql.SQLException;
import oracle.apps.xdo.XDOException;
import com.sun.java.util.collections.Hashtable;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ARInvoiceOnlineAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public ARInvoiceOnlineAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.awcust.ar.reports.server", /* package name */
      "ARInvoiceOnlineAMLocal" /* Configuration Name */);
    }
    public BlobDomain getXMLData (String strInvoiceNumber)
    {
    BlobDomain blobDomain = new BlobDomain();
    try
    {
    DataTemplate datatemplate = new DataTemplate(((OADBTransactionImpl)getOADBTransaction()).getAppsContext(), "AWCUST", "XX_AR_ONLINE_INVOICE");
    Hashtable parameters = new Hashtable();
    parameters.put("P_INVOICE_NUMBER",strInvoiceNumber);
    datatemplate.setParameters(parameters);
    datatemplate.setOutput(blobDomain.getBinaryOutputStream());
    datatemplate.processData();
    }
    catch(SQLException e)
    {
    throw new OAException("SQL Error=" + e.getMessage(),OAException.ERROR);
    }
    catch (XDOException e)
    {
    throw new OAException("XDOException" + e.getMessage(),OAException.ERROR);
    }
    catch(Exception e)
    {
    throw new OAException("Exception" + e.getMessage(),OAException.ERROR);
    }
    return blobDomain;
    }
}
