--------------------------------------------------------
--  File created - Thursday-September-19-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Trigger XX_CE_BANK_ACCOUNTS_INS1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "APPS"."XX_CE_BANK_ACCOUNTS_INS1" 
/******************************************************************************
--NAME:      XX_CE_BANK_ACCOUNTS_INS1 Trigger
--PURPOSE:   To snapshot the history of the bank account when created
--REVISIONS:
--Ver        Date        Author           Description
-----------  ----------  ---------------  ------------------------------------
--1.0        25/07/2013  S Joyce          Created this trigger for R12
******************************************************************************/
AFTER
   INSERT
      ON CE.CE_BANK_ACCOUNTS FOR EACH ROW BEGIN
   INSERT
   INTO
      xx_bank_account_hist_2 VALUES
       (
      :new.BANK_ACCOUNT_ID               ,
      :new.BANK_ACCOUNT_NAME             ,
      :new.LAST_UPDATE_DATE              ,
      :new.LAST_UPDATED_BY               ,
      :new.LAST_UPDATE_LOGIN             ,
      :new.CREATION_DATE                 ,
      :new.CREATED_BY                    ,
      :new.BANK_ACCOUNT_NUM              ,
      :new.BANK_BRANCH_ID                ,
      :new.BANK_ID                       ,
      :new.CURRENCY_CODE                 ,
      :new.DESCRIPTION                   ,
      :new.ATTRIBUTE_CATEGORY            ,
      :new.ATTRIBUTE1                    ,
      :new.ATTRIBUTE2                    ,
      :new.ATTRIBUTE3                    ,
      :new.ATTRIBUTE4                    ,
      :new.ATTRIBUTE5                    ,
      :new.ATTRIBUTE6                    ,
      :new.ATTRIBUTE7                    ,
      :new.ATTRIBUTE8                    ,
      :new.ATTRIBUTE9                    ,
      :new.ATTRIBUTE10                   ,
      :new.ATTRIBUTE11                   ,
      :new.ATTRIBUTE12                   ,
      :new.ATTRIBUTE13                   ,
      :new.ATTRIBUTE14                   ,
      :new.ATTRIBUTE15                   ,
      :new.REQUEST_ID                    ,
      :new.PROGRAM_APPLICATION_ID        ,
      :new.PROGRAM_ID                    ,
      :new.PROGRAM_UPDATE_DATE           ,
      :new.CHECK_DIGITS                  ,
      :new.BANK_ACCOUNT_NAME_ALT         ,
      :new.ACCOUNT_HOLDER_ID             ,
      :new.EFT_REQUESTER_IDENTIFIER      ,
      :new.SECONDARY_ACCOUNT_REFERENCE   ,
      :new.ACCOUNT_SUFFIX                ,
      :new.DESCRIPTION_CODE1             ,
      :new.DESCRIPTION_CODE2             ,
      :new.IBAN_NUMBER                   ,
      :new.SHORT_ACCOUNT_NAME            ,
      :new.ACCOUNT_OWNER_PARTY_ID        ,
      :new.ACCOUNT_OWNER_ORG_ID          ,
      :new.ACCOUNT_CLASSIFICATION        ,
      :new.AP_USE_ALLOWED_FLAG           ,
      :new.AR_USE_ALLOWED_FLAG           ,
      :new.XTR_USE_ALLOWED_FLAG          ,
      :new.PAY_USE_ALLOWED_FLAG          ,
      :new.MULTI_CURRENCY_ALLOWED_FLAG   ,
      :new.PAYMENT_MULTI_CURRENCY_FLAG   ,
      :new.RECEIPT_MULTI_CURRENCY_FLAG   ,
      :new.ZERO_AMOUNT_ALLOWED           ,
      :new.MAX_OUTLAY                    ,
      :new.MAX_CHECK_AMOUNT              ,
      :new.MIN_CHECK_AMOUNT              ,
      :new.AP_AMOUNT_TOLERANCE           ,
      :new.AR_AMOUNT_TOLERANCE           ,
      :new.XTR_AMOUNT_TOLERANCE          ,
      :new.PAY_AMOUNT_TOLERANCE          ,
      :new.AP_PERCENT_TOLERANCE          ,
      :new.AR_PERCENT_TOLERANCE          ,
      :new.XTR_PERCENT_TOLERANCE         ,
      :new.PAY_PERCENT_TOLERANCE         ,
      :new.BANK_ACCOUNT_TYPE             ,
      :new.AGENCY_LOCATION_CODE          ,
      :new.START_DATE                    ,
      :new.END_DATE                      ,
      :new.ACCOUNT_HOLDER_NAME_ALT       ,
      :new.ACCOUNT_HOLDER_NAME           ,
      :new.CASHFLOW_DISPLAY_ORDER        ,
      :new.POOLED_FLAG                   ,
      :new.MIN_TARGET_BALANCE            ,
      :new.MAX_TARGET_BALANCE            ,
      :new.EFT_USER_NUM                  ,
      :new.MASKED_ACCOUNT_NUM            ,
      :new.MASKED_IBAN                   ,
      :new.INTEREST_SCHEDULE_ID          ,
      :new.CASHPOOL_MIN_PAYMENT_AMT      ,
      :new.CASHPOOL_MIN_RECEIPT_AMT      ,
      :new.CASHPOOL_ROUND_FACTOR         ,
      :new.CASHPOOL_ROUND_RULE           ,
      :new.CE_AMOUNT_TOLERANCE           ,
      :new.CE_PERCENT_TOLERANCE          ,
      :new.ASSET_CODE_COMBINATION_ID     ,
      :new.CASH_CLEARING_CCID            ,
      :new.BANK_CHARGES_CCID             ,
      :new.BANK_ERRORS_CCID              ,
      :new.OBJECT_VERSION_NUMBER         ,
      :new.NETTING_ACCT_FLAG             ,
      :new.POOL_PAYMENT_METHOD_CODE      ,
      :new.POOL_BANK_CHARGE_BEARER_CODE  ,
      :new.POOL_PAYMENT_REASON_CODE      ,
      :new.POOL_PAYMENT_REASON_COMMENTS  ,
      :new.POOL_REMITTANCE_MESSAGE1      ,
      :new.POOL_REMITTANCE_MESSAGE2      ,
      :new.POOL_REMITTANCE_MESSAGE3      ,
      :new.FX_CHARGE_CCID                ,
      :new.BANK_ACCOUNT_NUM_ELECTRONIC   ,
      :new.STMT_LINE_FLOAT_HANDLING_FLAG ,
      :new.AUTORECON_AP_MATCHING_ORDER   ,
      :new.AUTORECON_AR_MATCHING_ORDER   ,
      :new.RECON_FOREIGN_BANK_XRATE_TYPE ,
      :new.RECON_FOR_BANK_XRATE_DATE_TYPE,
      :new.RECON_ENABLE_OI_FLAG          ,
      :new.RECON_OI_FLOAT_STATUS         ,
      :new.RECON_OI_CLEARED_STATUS       ,
      :new.RECON_OI_MATCHING_CODE        ,
      :new.RECON_OI_AMOUNT_TOLERANCE     ,
      :new.RECON_OI_PERCENT_TOLERANCE    ,
      :new.MANUAL_RECON_AMOUNT_TOLERANCE ,
      :new.MANUAL_RECON_PERCENT_TOLERANCE,
      :new.RECON_AP_FOREIGN_DIFF_HANDLING,
      :new.RECON_AR_FOREIGN_DIFF_HANDLING,
      :new.RECON_CE_FOREIGN_DIFF_HANDLING,
      :new.RECON_AP_TOLERANCE_DIFF_ACCT  ,
      :new.RECON_CE_TOLERANCE_DIFF_ACCT  ,
      :new.XTR_BANK_ACCOUNT_REFERENCE    ,
      :new.AUTORECON_AP_MATCHING_ORDER2  ,
      :new.GAIN_CODE_COMBINATION_ID      ,
      :new.LOSS_CODE_COMBINATION_ID      ,
      :new.BANK_ACCOUNT_ID
   );

END;
/
ALTER TRIGGER "APPS"."XX_CE_BANK_ACCOUNTS_INS1" ENABLE;
