package oracle.apps.awcust.person.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserProfileVORowImpl extends OAViewRowImpl {
    public static final int USERPROFILE = 0;
    public static final int DESCRIPTION = 1;

    /**This is the default constructor (do not remove)
     */
    public UserProfileVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute UserProfile
     */
    public String getUserProfile() {
        return (String) getAttributeInternal(USERPROFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UserProfile
     */
    public void setUserProfile(String value) {
        setAttributeInternal(USERPROFILE, value);
    }

    /**Gets the attribute value for the calculated attribute Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case USERPROFILE:
            return getUserProfile();
        case DESCRIPTION:
            return getDescription();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
