package oracle.apps.awcust.awcustPerson;
import oracle.jbo.Row;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 * 
 * Generated interface. Do not modify.
 */

public interface awcustPersonDetailsVORow extends Row 
{
  oracle.jbo.domain.Number getPersonId();

  void setStatus(String value);





}