package oracle.apps.awcust.awcustPerson.schema.server;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class awcustPersonDetailsEODefImpl extends OAEntityDefImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public awcustPersonDetailsEODefImpl()
  {
  }
}