package oracle.apps.awcust.awcustPerson.server;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class awcustGenericAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public awcustGenericAMImpl()
  {
  }

  /**
   * 
   * Container's getter for awcustCostCentreVO1
   */
  public awcustCostCentreVOImpl getawcustCostCentreVO1()
  {
    return (awcustCostCentreVOImpl)findViewObject("awcustCostCentreVO1");
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("oracle.apps.awcust.awcustPerson.server", "awcustGenericAMLocal");
  }

  /**
   * 
   * Container's getter for awcustLocationVO1
   */
  public awcustLocationVOImpl getawcustLocationVO1()
  {
    return (awcustLocationVOImpl)findViewObject("awcustLocationVO1");
  }

  /**
   * 
   * Container's getter for awcustManagerVO1
   */
  public awcustManagerVOImpl getawcustManagerVO1()
  {
    return (awcustManagerVOImpl)findViewObject("awcustManagerVO1");
  }

  /**
   * 
   * Container's getter for awcustDepartmentVO1
   */
  public awcustDepartmentVOImpl getawcustDepartmentVO1()
  {
    return (awcustDepartmentVOImpl)findViewObject("awcustDepartmentVO1");
  }
}