package oracle.apps.awcust.person.server.common;

import com.sun.java.util.collections.List;

import java.io.Serializable;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

import oracle.svc.DataCriteria;
import oracle.svc.DataObject;
import oracle.svc.QueryControl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface EmpDetailsCreateVORow extends Row {
    DataObject getDataObject(DataCriteria param, QueryControl param2);

    DataObject getDataObject(DataCriteria param, QueryControl param2, boolean param3);int[] getExposedAttributeIndexes(String[] param);

    String[] getExposedAttributeNames(DataCriteria param);

    byte getPostState();

    String[] getTranslatedLanguages();

    Serializable invokeMethod(String param);

    Serializable invokeMethod(String param, Serializable[] param2);

    Serializable invokeMethod(String param, Serializable[] param2, 
                              Class[] param3);

    boolean isTranslatable();

    boolean isTranslatableAttribute(int param);

    boolean isTranslated();

    void remove();

    void setAttributes(List param);

    void validate();

    String getCopyUserFrom();

    Number getCreatedBy();

    Date getCreationDate();

    String getCreditCard();

    String getEmail();

    Number getExternalPersonId();

    String getFirstName();

    String getLastName();

    Date getLastUpdateDate();

    Number getLastUpdateLogin();

    Number getLastUpdatedBy();

    Number getPapPersonId();

    Number getPersonId();

    String getStatus();

    Number getUserId();

    void setCopyUserFrom(String value);

    void setCreatedBy(Number value);

    void setCreationDate(Date value);

    void setCreditCard(String value);

    void setEmail(String value);

    void setExternalPersonId(Number value);

    void setFirstName(String value);

    void setLastName(String value);

    void setLastUpdateDate(Date value);

    void setLastUpdateLogin(Number value);

    void setLastUpdatedBy(Number value);

    void setPapPersonId(Number value);

    void setPersonId(Number value);

    void setStatus(String value);

    void setUserId(Number value);
}
