--------------------------------------------------------
--  File created - Thursday-August-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XX_AP_INVOICE_HEADER_IF
--------------------------------------------------------

  CREATE TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" 
   (	"BATCH_ID" VARCHAR2(20 BYTE), 
	"INVOICE_ID" NUMBER, 
	"VENDOR_SITE_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(40 BYTE), 
	"INVOICE_DATE" DATE, 
	"INVOICE_CURRENCY" VARCHAR2(3 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_RECEIVED_DATE" DATE, 
	"DESCRIPTION2" VARCHAR2(100 BYTE), 
	"NUM_OF_DISTS" NUMBER, 
	"NET_INVOICE_AMT" NUMBER, 
	"TOTAL_TAX_AMT" NUMBER, 
	"VAT1PC" NUMBER, 
	"VAT1AMT" NUMBER, 
	"VAT2PC" NUMBER, 
	"VAT2AMT" NUMBER, 
	"VAT3PC" NUMBER, 
	"VAT3AMT" NUMBER, 
	"VAT4PC" NUMBER, 
	"VAT4AMT" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"RECORD_TYPE" VARCHAR2(20 BYTE), 
	"VENDOR_NAME" VARCHAR2(200 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"FINAL_APPROVER" VARCHAR2(200 BYTE), 
	"FINAL_APP_COMMENTS" VARCHAR2(400 BYTE), 
	"VENDOR_COUNTRY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table XX_AP_INVOICE_HEADER_IF
--------------------------------------------------------

  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("INVOICE_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("INVOICE_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("INVOICE_RECEIVED_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("NUM_OF_DISTS" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("NET_INVOICE_AMT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_HEADER_IF" MODIFY ("TOTAL_TAX_AMT" NOT NULL ENABLE);
