DROP PACKAGE "APPS"."XX_GL_INTERCO_HUB_PKG";
/
DROP PACKAGE "APPS"."XX_GL_INTERCO";
/
DROP PACKAGE "APPS"."XX_AP_IMPORT_INVOICES_PKG";
/
DROP PACKAGE "APPS"."XX_AP_IMSCAN_IMPORT_PKG";
/
DROP PACKAGE "APPS"."XX_AP_IMSCAN_UTILITIES_PKG";
/
drop package "APPS"."XX_AP_INVOICE_APRVL";
/
DROP PACKAGE "APPS"."XX_AP_APPROVAL_WF";
/
DROP TRIGGER "APPS"."XX_BANK_ACCOUNT_INS_1";
/
DROP TRIGGER "APPS"."XXAP_BANK_ACCOUNTS_INS1";
/
DROP TRIGGER "APPS"."XXAP_BANK_ACCOUNTS_UP1";
/
DROP VIEW "APPS"."VDGACCSTATUS";
/
DROP VIEW "APPS"."XX_AP_IMSCAN_IF_ERRORS";
/
DROP VIEW "APPS"."XX_IMSCAN_GL_VALUES_V";
/
DROP VIEW "APPS"."XX_IMSCAN_PAY_GROUPS";
/
DROP VIEW "APPS"."XX_IMSCAN_PAY_GROUPS_V";
/
DROP VIEW "APPS"."XX_IMSCAN_SUPPLIER_MASTER_V";
/
DROP VIEW "APPS"."XX_IMSCAN_TAX_CODES";
/
DROP VIEW "APPS"."XX_IMSCAN_TAX_CODES_V";
/
DROP PACKAGE "APPS"."XX_AP_CITI_PREFORMAT_PKG";
/
TRUNCATE TABLE APPLSYS.FND_FOLDERS;
/
TRUNCATE TABLE APPLSYS.FND_DEFAULT_FOLDERS;
/
TRUNCATE TABLE APPLSYS.FND_FOLDER_COLUMNS;
/
