--------------------------------------------------------
--  File created - Thursday-August-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XX_AP_INVOICE_BATCH_IF
--------------------------------------------------------

  CREATE TABLE "APPS"."XX_AP_INVOICE_BATCH_IF" 
   (	"BATCH_ID" VARCHAR2(60 BYTE), 
	"BATCH_DATE" DATE, 
	"CREATED_BY_NAME" VARCHAR2(60 BYTE), 
	"INVOICE_COUNT" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"RECORD_TYPE" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table XX_AP_INVOICE_BATCH_IF
--------------------------------------------------------

  ALTER TABLE "APPS"."XX_AP_INVOICE_BATCH_IF" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_BATCH_IF" MODIFY ("BATCH_DATE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_BATCH_IF" MODIFY ("CREATED_BY_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_BATCH_IF" MODIFY ("INVOICE_COUNT" NOT NULL ENABLE);
