package oracle.apps.awcust.person.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeDetailsEOImpl extends OAEntityImpl {
    public static final int PERSONID = 0;
    public static final int FIRSTNAME = 1;
    public static final int LASTNAME = 2;
    public static final int COPYUSERFROM = 3;
    public static final int STATUS = 4;
    public static final int EMAIL = 5;
    public static final int USERID = 6;
    public static final int PAPPERSONID = 7;
    public static final int EXTERNALPERSONID = 8;
    public static final int LASTUPDATEDATE = 9;
    public static final int LASTUPDATELOGIN = 10;
    public static final int LASTUPDATEDBY = 11;
    public static final int CREATIONDATE = 12;
    public static final int CREATEDBY = 13;
    public static final int CREDITCARD = 14;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public EmployeeDetailsEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.awcust.person.server.EmployeeDetailsEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for PersonId, using the alias name PersonId
     */
    public Number getPersonId() {
        return (Number)getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for FirstName, using the alias name FirstName
     */
    public String getFirstName() {
        return (String)getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as the attribute value for FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for LastName, using the alias name LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for CopyUserFrom, using the alias name CopyUserFrom
     */
    public String getCopyUserFrom() {
        return (String)getAttributeInternal(COPYUSERFROM);
    }

    /**Sets <code>value</code> as the attribute value for CopyUserFrom
     */
    public void setCopyUserFrom(String value) {
        setAttributeInternal(COPYUSERFROM, value);
    }

    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for Email, using the alias name Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as the attribute value for Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for UserId, using the alias name UserId
     */
    public Number getUserId() {
        return (Number)getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as the attribute value for UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for PapPersonId, using the alias name PapPersonId
     */
    public Number getPapPersonId() {
        return (Number)getAttributeInternal(PAPPERSONID);
    }

    /**Sets <code>value</code> as the attribute value for PapPersonId
     */
    public void setPapPersonId(Number value) {
        setAttributeInternal(PAPPERSONID, value);
    }

    /**Gets the attribute value for ExternalPersonId, using the alias name ExternalPersonId
     */
    public Number getExternalPersonId() {
        return (Number)getAttributeInternal(EXTERNALPERSONID);
    }

    /**Sets <code>value</code> as the attribute value for ExternalPersonId
     */
    public void setExternalPersonId(Number value) {
        setAttributeInternal(EXTERNALPERSONID, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreditCard, using the alias name CreditCard
     */
    public String getCreditCard() {
        return (String)getAttributeInternal(CREDITCARD);
    }

    /**Sets <code>value</code> as the attribute value for CreditCard
     */
    public void setCreditCard(String value) {
        setAttributeInternal(CREDITCARD, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case COPYUSERFROM:
            return getCopyUserFrom();
        case STATUS:
            return getStatus();
        case EMAIL:
            return getEmail();
        case USERID:
            return getUserId();
        case PAPPERSONID:
            return getPapPersonId();
        case EXTERNALPERSONID:
            return getExternalPersonId();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case CREDITCARD:
            return getCreditCard();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            setPersonId((Number)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case COPYUSERFROM:
            setCopyUserFrom((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case USERID:
            setUserId((Number)value);
            return;
        case PAPPERSONID:
            setPapPersonId((Number)value);
            return;
        case EXTERNALPERSONID:
            setExternalPersonId((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREDITCARD:
            setCreditCard((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number personId) {
        return new Key(new Object[]{personId});
    }
}
