--------------------------------------------------------
--  File created - Thursday-August-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XX_AP_INVOICE_LINES_IF
--------------------------------------------------------

  CREATE TABLE "APPS"."XX_AP_INVOICE_LINES_IF" 
   (	"INVOICE_ID" NUMBER, 
	"ROW_NUMBER" NUMBER, 
	"ENTITY" VARCHAR2(100 BYTE), 
	"ACCOUNT" VARCHAR2(100 BYTE), 
	"COST_CENTRE" VARCHAR2(100 BYTE), 
	"MSN" VARCHAR2(100 BYTE), 
	"LEASEE" VARCHAR2(100 BYTE), 
	"AMOUNT" NUMBER, 
	"NET_AMOUNT" NUMBER, 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"GL_CODE_COMBINATION_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"RECORD_TYPE" VARCHAR2(20 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table XX_AP_INVOICE_LINES_IF
--------------------------------------------------------

  ALTER TABLE "APPS"."XX_AP_INVOICE_LINES_IF" MODIFY ("INVOICE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_LINES_IF" MODIFY ("ROW_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_LINES_IF" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "APPS"."XX_AP_INVOICE_LINES_IF" MODIFY ("NET_AMOUNT" NOT NULL ENABLE);
