package oracle.apps.awcust.awcustPerson.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class awcustLocationVORowImpl extends OAViewRowImpl 
{





  protected static final int LOCATIONCODE = 0;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public awcustLocationVORowImpl()
  {
  }



  /**
   * 
   * Gets the attribute value for the calculated attribute LocationCode
   */
  public String getLocationCode()
  {
    return (String)getAttributeInternal(LOCATIONCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute LocationCode
   */
  public void setLocationCode(String value)
  {
    setAttributeInternal(LOCATIONCODE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LOCATIONCODE:
        return getLocationCode();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case LOCATIONCODE:
        setLocationCode((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}