package oracle.apps.awcust.person.server;

import oracle.apps.awcust.person.server.common.EmpDetailsCreateVORow;
import oracle.apps.fnd.framework.server.OAEntityImpl;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDetailsCreateVORowImpl extends OAViewRowImpl implements EmpDetailsCreateVORow {
    public static final int PERSONID = 0;
    public static final int FIRSTNAME = 1;
    public static final int LASTNAME = 2;
    public static final int COPYUSERFROM = 3;
    public static final int STATUS = 4;
    public static final int EMAIL = 5;
    public static final int USERID = 6;
    public static final int PAPPERSONID = 7;
    public static final int EXTERNALPERSONID = 8;
    public static final int LASTUPDATEDATE = 9;
    public static final int LASTUPDATELOGIN = 10;
    public static final int LASTUPDATEDBY = 11;
    public static final int CREATIONDATE = 12;
    public static final int CREATEDBY = 13;
    public static final int CREDITCARD = 14;

    /**This is the default constructor (do not remove)
     */
    public EmpDetailsCreateVORowImpl() {
    }

    /**Gets EmployeeDetailsEO entity object.
     */
    public EmployeeDetailsEOImpl getEmployeeDetailsEO() {
        return (EmployeeDetailsEOImpl)getEntity(0);
    }

    /**Gets the attribute value for PERSON_ID using the alias name PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId
     */
    public void setPersonId(Number value) {
    
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for FIRST_NAME using the alias name FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for LAST_NAME using the alias name LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for COPY_USER_FROM using the alias name CopyUserFrom
     */
    public String getCopyUserFrom() {
        return (String) getAttributeInternal(COPYUSERFROM);
    }

    /**Sets <code>value</code> as attribute value for COPY_USER_FROM using the alias name CopyUserFrom
     */
    public void setCopyUserFrom(String value) {
        setAttributeInternal(COPYUSERFROM, value);
    }

    /**Gets the attribute value for STATUS using the alias name Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as attribute value for STATUS using the alias name Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for EMAIL using the alias name Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as attribute value for EMAIL using the alias name Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for USER_ID using the alias name UserId
     */
    public Number getUserId() {
        return (Number) getAttributeInternal(USERID);
    }

    /**Sets <code>value</code> as attribute value for USER_ID using the alias name UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**Gets the attribute value for PAP_PERSON_ID using the alias name PapPersonId
     */
    public Number getPapPersonId() {
        return (Number) getAttributeInternal(PAPPERSONID);
    }

    /**Sets <code>value</code> as attribute value for PAP_PERSON_ID using the alias name PapPersonId
     */
    public void setPapPersonId(Number value) {
        setAttributeInternal(PAPPERSONID, value);
    }

    /**Gets the attribute value for EXTERNAL_PERSON_ID using the alias name ExternalPersonId
     */
    public Number getExternalPersonId() {
        return (Number) getAttributeInternal(EXTERNALPERSONID);
    }

    /**Sets <code>value</code> as attribute value for EXTERNAL_PERSON_ID using the alias name ExternalPersonId
     */
    public void setExternalPersonId(Number value) {
        setAttributeInternal(EXTERNALPERSONID, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case COPYUSERFROM:
            return getCopyUserFrom();
        case STATUS:
            return getStatus();
        case EMAIL:
            return getEmail();
        case USERID:
            return getUserId();
        case PAPPERSONID:
            return getPapPersonId();
        case EXTERNALPERSONID:
            return getExternalPersonId();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case CREDITCARD:
            return getCreditCard();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            setPersonId((Number)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case COPYUSERFROM:
            setCopyUserFrom((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case USERID:
            setUserId((Number)value);
            return;
        case PAPPERSONID:
            setPapPersonId((Number)value);
            return;
        case EXTERNALPERSONID:
            setExternalPersonId((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREDITCARD:
            setCreditCard((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for CREDIT_CARD using the alias name CreditCard
     */
    public String getCreditCard() {
        return (String) getAttributeInternal(CREDITCARD);
    }

    /**Sets <code>value</code> as attribute value for CREDIT_CARD using the alias name CreditCard
     */
    public void setCreditCard(String value) {
        setAttributeInternal(CREDITCARD, value);
    }
}
