package oracle.apps.awcust.person.server.client;

import com.sun.java.util.collections.List;

import java.io.Serializable;

import oracle.apps.awcust.person.server.common.EmpDetailsCreateVORow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

import oracle.svc.DataCriteria;
import oracle.svc.DataObject;
import oracle.svc.QueryControl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDetailsCreateVORowClient extends RowImpl implements EmpDetailsCreateVORow {
    /**This is the default constructor (do not remove)
     */
    public EmpDetailsCreateVORowClient() {
    }


    public DataObject getDataObject(DataCriteria param, QueryControl param2) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getDataObject",new String [] {"oracle.svc.DataCriteria","oracle.svc.QueryControl"},new Object[] {param, param2});
        return (DataObject)_ret;
    }

    public DataObject getDataObject(DataCriteria param, QueryControl param2, 
                                    boolean param3) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getDataObject",new String [] {"oracle.svc.DataCriteria","oracle.svc.QueryControl","boolean"},new Object[] {param, param2, new Boolean(param3)});
        return (DataObject)_ret;
    }

    public int[] getExposedAttributeIndexes(String[] param) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getExposedAttributeIndexes",new String [] {"[Ljava.lang.String;"},new Object[] {param});
        return (int[])_ret;
    }

    public String[] getExposedAttributeNames(DataCriteria param) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getExposedAttributeNames",new String [] {"oracle.svc.DataCriteria"},new Object[] {param});
        return (String[])_ret;
    }

    public byte getPostState() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getPostState",null,null);
        return ((Byte)_ret).byteValue();
    }

    public String[] getTranslatedLanguages() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getTranslatedLanguages",null,null);
        return (String[])_ret;
    }

    public Serializable invokeMethod(String param) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"invokeMethod",new String [] {"java.lang.String"},new Object[] {param});
        return (Serializable)_ret;
    }

    public Serializable invokeMethod(String param, Serializable[] param2) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"invokeMethod",new String [] {"java.lang.String","[Ljava.io.Serializable;"},new Object[] {param, param2});
        return (Serializable)_ret;
    }

    public Serializable invokeMethod(String param, Serializable[] param2, 
                                     Class[] param3) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"invokeMethod",new String [] {"java.lang.String","[Ljava.io.Serializable;","[Ljava.lang.Class;"},new Object[] {param, param2, param3});
        return (Serializable)_ret;
    }

    public boolean isTranslatable() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"isTranslatable",null,null);
        return ((Boolean)_ret).booleanValue();
    }

    public boolean isTranslatableAttribute(int param) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"isTranslatableAttribute",new String [] {"int"},new Object[] {new Integer(param)});
        return ((Boolean)_ret).booleanValue();
    }

    public boolean isTranslated() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"isTranslated",null,null);
        return ((Boolean)_ret).booleanValue();
    }

    public void remove() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"remove",null,null);
        return;
    }

    public void setAttributes(List param) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setAttributes",new String [] {"com.sun.java.util.collections.List"},new Object[] {param});
        return;
    }

    public void validate() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"validate",null,null);
        return;
    }

    public String getCopyUserFrom() {
        return (String)getAttribute("CopyUserFrom");
    }

    public Number getCreatedBy() {
        return (Number)getAttribute("CreatedBy");
    }

    public Date getCreationDate() {
        return (Date)getAttribute("CreationDate");
    }

    public String getCreditCard() {
        return (String)getAttribute("CreditCard");
    }

    public String getEmail() {
        return (String)getAttribute("Email");
    }

    public Number getExternalPersonId() {
        return (Number)getAttribute("ExternalPersonId");
    }

    public String getFirstName() {
        return (String)getAttribute("FirstName");
    }

    public String getLastName() {
        return (String)getAttribute("LastName");
    }

    public Date getLastUpdateDate() {
        return (Date)getAttribute("LastUpdateDate");
    }

    public Number getLastUpdateLogin() {
        return (Number)getAttribute("LastUpdateLogin");
    }

    public Number getLastUpdatedBy() {
        return (Number)getAttribute("LastUpdatedBy");
    }

    public Number getPapPersonId() {
        return (Number)getAttribute("PapPersonId");
    }

    public Number getPersonId() {
        return (Number)getAttribute("PersonId");
    }

    public String getStatus() {
        return (String)getAttribute("Status");
    }

    public Number getUserId() {
        return (Number)getAttribute("UserId");
    }

    public void setCopyUserFrom(String value) {
        setAttribute("CopyUserFrom", value);
    }

    public void setCreatedBy(Number value) {
        setAttribute("CreatedBy", value);
    }

    public void setCreationDate(Date value) {
        setAttribute("CreationDate", value);
    }

    public void setCreditCard(String value) {
        setAttribute("CreditCard", value);
    }

    public void setEmail(String value) {
        setAttribute("Email", value);
    }

    public void setExternalPersonId(Number value) {
        setAttribute("ExternalPersonId", value);
    }

    public void setFirstName(String value) {
        setAttribute("FirstName", value);
    }

    public void setLastName(String value) {
        setAttribute("LastName", value);
    }

    public void setLastUpdateDate(Date value) {
        setAttribute("LastUpdateDate", value);
    }

    public void setLastUpdateLogin(Number value) {
        setAttribute("LastUpdateLogin", value);
    }

    public void setLastUpdatedBy(Number value) {
        setAttribute("LastUpdatedBy", value);
    }

    public void setPapPersonId(Number value) {
        setAttribute("PapPersonId", value);
    }

    public void setPersonId(Number value) {
        setAttribute("PersonId", value);
    }

    public void setStatus(String value) {
        setAttribute("Status", value);
    }

    public void setUserId(Number value) {
        setAttribute("UserId", value);
    }
}
